echo "18个实验后台执行开始, Compute Node: 211 ....."
#【base-47】 --instance_loss_ensemble --ensemble_rate 0.1 --ensemble_strategy "geomethric" :: 
CUDA_VISIBLE_DEVICES=4 python main.py --model_name "Thumos14_CLIP_description_zs50_8frame_v3_91" --cfg_path "./config/Thumos14_CLIP_zs_50_8frame.yaml" --use_mlflow --save_result --batch_size 16 --target_type "description" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --cls_loss_coef 1 --instance_loss --instance_head_type "MHA" --semantic_head_version "v2" --lr_semantic_head 1e-8 --subaction_version "v2" --instance_loss_ensemble --ensemble_rate 0.1 --ensemble_strategy "geomethric" &
sleep 3
#【base-48】 --instance_loss_ensemble --ensemble_rate 0.1 --ensemble_strategy "geomethric" :: 
CUDA_VISIBLE_DEVICES=4 python main.py --model_name "Thumos14_CLIP_description_zs50_8frame_v3_92" --cfg_path "./config/Thumos14_CLIP_zs_50_8frame.yaml" --use_mlflow --save_result --batch_size 16 --target_type "description" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --cls_loss_coef 1 --instance_loss --instance_head_type "MHA" --semantic_head_version "v2" --lr_semantic_head 1e-8 --subaction_version "v3" --instance_loss_ensemble --ensemble_rate 0.1 --ensemble_strategy "geomethric" &
sleep 3
#【base-33】 --instance_loss_ensemble --ensemble_rate 0.1 --ensemble_strategy "geomethric" :: 
CUDA_VISIBLE_DEVICES=4 python main.py --model_name "Thumos14_CLIP_description_zs50_8frame_v3_93" --cfg_path "./config/Thumos14_CLIP_zs_50_8frame.yaml" --use_mlflow --save_result --batch_size 16 --target_type "description" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --cls_loss_coef 1 --instance_loss --instance_head_type "Conv" --lr_semantic_head 1e-7 --subaction_version "v3" --instance_loss_ensemble --ensemble_rate 0.1 --ensemble_strategy "geomethric" &
sleep 3
#【base-30】 --instance_loss_ensemble --ensemble_rate 0.1 --ensemble_strategy "geomethric" :: 
CUDA_VISIBLE_DEVICES=5 python main.py --model_name "Thumos14_CLIP_description_zs50_8frame_v3_94" --cfg_path "./config/Thumos14_CLIP_zs_50_8frame.yaml" --use_mlflow --save_result --batch_size 16 --target_type "description" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --cls_loss_coef 1 --instance_loss --instance_head_type "Conv" --lr_semantic_head 1e-7 --subaction_version "v2" --instance_loss_ensemble --ensemble_rate 0.1 --ensemble_strategy "geomethric" &
sleep 3
#【base-17】 --instance_loss_ensemble --ensemble_rate 0.1 --ensemble_strategy "geomethric" :: 
CUDA_VISIBLE_DEVICES=5 python main.py --model_name "Thumos14_CLIP_description_zs50_8frame_v2_95" --cfg_path "./config/Thumos14_CLIP_zs_50_8frame.yaml" --use_mlflow --save_result --batch_size 16 --target_type "description" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --cls_loss_coef 1 --instance_loss --instance_head_type "MHA" --lr_semantic_head 1e-7 --subaction_version "v2" --instance_loss_ensemble --ensemble_rate 0.1 --ensemble_strategy "geomethric" &
sleep 3
#【base-18】 --instance_loss_ensemble --ensemble_rate 0.1 --ensemble_strategy "geomethric" :: 
CUDA_VISIBLE_DEVICES=5 python main.py --model_name "Thumos14_CLIP_description_zs50_8frame_v2_96" --cfg_path "./config/Thumos14_CLIP_zs_50_8frame.yaml" --use_mlflow --save_result --batch_size 16 --target_type "description" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --cls_loss_coef 1 --instance_loss --instance_head_type "MHA" --lr_semantic_head 1e-7 --subaction_version "v3" --instance_loss_ensemble --ensemble_rate 0.1 --ensemble_strategy "geomethric" &
sleep 3
#【base-47】 --instance_loss_ensemble --ensemble_rate 0.1  :: 
CUDA_VISIBLE_DEVICES=6 python main.py --model_name "Thumos14_CLIP_description_zs50_8frame_v3_97" --cfg_path "./config/Thumos14_CLIP_zs_50_8frame.yaml" --use_mlflow --save_result --batch_size 16 --target_type "description" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --cls_loss_coef 1 --instance_loss --instance_head_type "MHA" --semantic_head_version "v2" --lr_semantic_head 1e-8 --subaction_version "v2" --instance_loss_ensemble --ensemble_rate 0.1 &
sleep 3
#【base-48】 --instance_loss_ensemble --ensemble_rate 0.1  :: 
CUDA_VISIBLE_DEVICES=6 python main.py --model_name "Thumos14_CLIP_description_zs50_8frame_v3_98" --cfg_path "./config/Thumos14_CLIP_zs_50_8frame.yaml" --use_mlflow --save_result --batch_size 16 --target_type "description" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --cls_loss_coef 1 --instance_loss --instance_head_type "MHA" --semantic_head_version "v2" --lr_semantic_head 1e-8 --subaction_version "v3" --instance_loss_ensemble --ensemble_rate 0.1 &
sleep 3
#【base-33】 --instance_loss_ensemble --ensemble_rate 0.1  :: 
CUDA_VISIBLE_DEVICES=6 python main.py --model_name "Thumos14_CLIP_description_zs50_8frame_v3_99" --cfg_path "./config/Thumos14_CLIP_zs_50_8frame.yaml" --use_mlflow --save_result --batch_size 16 --target_type "description" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --cls_loss_coef 1 --instance_loss --instance_head_type "Conv" --lr_semantic_head 1e-7 --subaction_version "v3" --instance_loss_ensemble --ensemble_rate 0.1 &
sleep 3
#【base-30】 --instance_loss_ensemble --ensemble_rate 0.1  :: 
CUDA_VISIBLE_DEVICES=7 python main.py --model_name "Thumos14_CLIP_description_zs50_8frame_v3_100" --cfg_path "./config/Thumos14_CLIP_zs_50_8frame.yaml" --use_mlflow --save_result --batch_size 16 --target_type "description" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --cls_loss_coef 1 --instance_loss --instance_head_type "Conv" --lr_semantic_head 1e-7 --subaction_version "v2" --instance_loss_ensemble --ensemble_rate 0.1 &
sleep 3
#【base-17】 --instance_loss_ensemble --ensemble_rate 0.1  :: 
CUDA_VISIBLE_DEVICES=7 python main.py --model_name "Thumos14_CLIP_description_zs50_8frame_v2_101" --cfg_path "./config/Thumos14_CLIP_zs_50_8frame.yaml" --use_mlflow --save_result --batch_size 16 --target_type "description" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --cls_loss_coef 1 --instance_loss --instance_head_type "MHA" --lr_semantic_head 1e-7 --subaction_version "v2" --instance_loss_ensemble --ensemble_rate 0.1 &
sleep 3
#【base-18】 --instance_loss_ensemble --ensemble_rate 0.1  :: 
CUDA_VISIBLE_DEVICES=7 python main.py --model_name "Thumos14_CLIP_description_zs50_8frame_v2_102" --cfg_path "./config/Thumos14_CLIP_zs_50_8frame.yaml" --use_mlflow --save_result --batch_size 16 --target_type "description" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --cls_loss_coef 1 --instance_loss --instance_head_type "MHA" --lr_semantic_head 1e-7 --subaction_version "v3" --instance_loss_ensemble --ensemble_rate 0.1 &
sleep 3
#【base-47】 --instance_loss_ensemble --ensemble_rate 0.01 --ensemble_strategy "geomethric" ::
CUDA_VISIBLE_DEVICES=3 python main.py --model_name "Thumos14_CLIP_description_zs50_8frame_v3_103" --cfg_path "./config/Thumos14_CLIP_zs_50_8frame.yaml" --use_mlflow --save_result --batch_size 16 --target_type "description" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --cls_loss_coef 1 --instance_loss --instance_head_type "MHA" --semantic_head_version "v2" --lr_semantic_head 1e-8 --subaction_version "v2" --instance_loss_ensemble --ensemble_rate 0.01 --ensemble_strategy "geomethric" &
sleep 3
#【base-47】 --instance_loss_ensemble --ensemble_rate 0.01  :: 
CUDA_VISIBLE_DEVICES=3 python main.py --model_name "Thumos14_CLIP_description_zs50_8frame_v3_104" --cfg_path "./config/Thumos14_CLIP_zs_50_8frame.yaml" --use_mlflow --save_result --batch_size 16 --target_type "description" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --cls_loss_coef 1 --instance_loss --instance_head_type "MHA" --semantic_head_version "v2" --lr_semantic_head 1e-8 --subaction_version "v2" --instance_loss_ensemble --ensemble_rate 0.01 &
sleep 3
#【base-47】 --instance_loss_ensemble --ensemble_rate 0 --ensemble_strategy "geomethric" ::
CUDA_VISIBLE_DEVICES=3 python main.py --model_name "Thumos14_CLIP_description_zs50_8frame_v3_105" --cfg_path "./config/Thumos14_CLIP_zs_50_8frame.yaml" --use_mlflow --save_result --batch_size 16 --target_type "description" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --cls_loss_coef 1 --instance_loss --instance_head_type "MHA" --semantic_head_version "v2" --lr_semantic_head 1e-8 --subaction_version "v2" --instance_loss_ensemble --ensemble_rate 0 --ensemble_strategy "geomethric" &
sleep 3
#【base-47】 --instance_loss_ensemble --ensemble_rate 0  :: 
CUDA_VISIBLE_DEVICES=2 python main.py --model_name "Thumos14_CLIP_description_zs50_8frame_v3_106" --cfg_path "./config/Thumos14_CLIP_zs_50_8frame.yaml" --use_mlflow --save_result --batch_size 16 --target_type "description" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --cls_loss_coef 1 --instance_loss --instance_head_type "MHA" --semantic_head_version "v2" --lr_semantic_head 1e-8 --subaction_version "v2" --instance_loss_ensemble --ensemble_rate 0 &
sleep 3
#【base-47】 --instance_loss_ensemble --ensemble_rate 1 --ensemble_strategy "geomethric" ::
CUDA_VISIBLE_DEVICES=2 python main.py --model_name "Thumos14_CLIP_description_zs50_8frame_v3_107" --cfg_path "./config/Thumos14_CLIP_zs_50_8frame.yaml" --use_mlflow --save_result --batch_size 16 --target_type "description" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --cls_loss_coef 1 --instance_loss --instance_head_type "MHA" --semantic_head_version "v2" --lr_semantic_head 1e-8 --subaction_version "v2" --instance_loss_ensemble --ensemble_rate 1 --ensemble_strategy "geomethric" &
sleep 3
#【base-47】 --instance_loss_ensemble --ensemble_rate 1  :: 
CUDA_VISIBLE_DEVICES=2 python main.py --model_name "Thumos14_CLIP_description_zs50_8frame_v3_108" --cfg_path "./config/Thumos14_CLIP_zs_50_8frame.yaml" --use_mlflow --save_result --batch_size 16 --target_type "description" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --cls_loss_coef 1 --instance_loss --instance_head_type "MHA" --semantic_head_version "v2" --lr_semantic_head 1e-8 --subaction_version "v2" --instance_loss_ensemble --ensemble_rate 1 &
wait
echo "18个实验后台执行结束, Compute Node: 211 ....."

