# Thumos14
# baseline:
## baseline :: 29.608 e55 (能复现)
CUDA_VISIBLE_DEVICES=4 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_1" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 5 --actionness_loss_coef 3 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic
## baseline: --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 :: e66 mAP: 18.709, AR@10: 12.11
CUDA_VISIBLE_DEVICES=6 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_1_verbs" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 5 --actionness_loss_coef 3 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1
## baseline: --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_coef 0.1 :: e42 mAP: 30.201, AR@10: 14.255 
CUDA_VISIBLE_DEVICES=5 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_1_verbs_1" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 5 --actionness_loss_coef 3 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_coef 0.1
## baseline: --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum" :: e11 mAP: 28.588, AR@10: 15.564
CUDA_VISIBLE_DEVICES=5 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_1_verbs_2" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 5 --actionness_loss_coef 3 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum"
## baseline: --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum" --adapterCLS_conv_add_verbs_coef 0.1 :: e40 mAP: 32.318, AR@10: 15.622
CUDA_VISIBLE_DEVICES=7 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_1_verbs_3" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 5 --actionness_loss_coef 3 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum" --adapterCLS_conv_add_verbs_coef 0.1
## baseline: --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum1" --adapterCLS_conv_add_verbs_coef 0.1 :: e21 mAP: 32.284, AR@10: 15.167
CUDA_VISIBLE_DEVICES=0 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_1_verbs_4" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 5 --actionness_loss_coef 3 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum1" --adapterCLS_conv_add_verbs_coef 0.1

# baseline + refine: 
## baseline + refine: --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 :: e90 mAP: 22.974, AR@10: 12.818
CUDA_VISIBLE_DEVICES=2 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_2_verbs" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 5 --actionness_loss_coef 3 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --enable_refine --refine_drop_saResidual --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1
## baseline + refine: --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_coef 0.1 :: e16 mAP: 32.723, AR@10: 13.881
CUDA_VISIBLE_DEVICES=3 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_2_verbs_1" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 5 --actionness_loss_coef 3 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --enable_refine --refine_drop_saResidual --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_coef 0.1
## baseline + refine: --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum" :: e45 mAP: 27.717, AR@10: 12.421
CUDA_VISIBLE_DEVICES=5 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_2_verbs_2" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 5 --actionness_loss_coef 3 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --enable_refine --refine_drop_saResidual --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum"
## baseline + refine: --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum" --adapterCLS_conv_add_verbs_coef 0.1 :: e40 mAP: 32.495, AR@10: 13.811
CUDA_VISIBLE_DEVICES=7 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_2_verbs_3" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 5 --actionness_loss_coef 3 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --enable_refine --refine_drop_saResidual --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum" --adapterCLS_conv_add_verbs_coef 0.1
## baseline + refine: --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum1" --adapterCLS_conv_add_verbs_coef 0.1 :: e45 mAP: 29.11, AR@10: 13.426
CUDA_VISIBLE_DEVICES=1 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_2_verbs_4" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 5 --actionness_loss_coef 3 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --enable_refine --refine_drop_saResidual --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum1" --adapterCLS_conv_add_verbs_coef 0.1



## baseline + refine :: e33 mAP: 34.919, AR@10: 15.891
CUDA_VISIBLE_DEVICES=4 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_2" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 5 --actionness_loss_coef 3 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --enable_refine --refine_drop_saResidual --refine_layer_num 2
## baseline + refine + refine_layer_num: --refine_layer_num 2 :: e33 mAP: 34.919, AR@10: 15.891
CUDA_VISIBLE_DEVICES=7 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_2_refineLayer" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 5 --actionness_loss_coef 3 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --enable_refine --refine_drop_saResidual --refine_layer_num 3

## baseline + refine + refine_cat_type 'sum' (sum是默认的，看看加了refine_cat_type有没有其他影响，能否复现上面的结果) :: 结果一致，没有写bug, :: e33 mAP: 34.919, AR@10: 15.891
CUDA_VISIBLE_DEVICES=4 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_2_refineCat" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 5 --actionness_loss_coef 3 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --enable_refine --refine_drop_saResidual --refine_cat_type 'sum'
## baseline + refine + refine_cat_type 'concat1' ::  e62 mAP: 30.346, AR@10: 14.232
CUDA_VISIBLE_DEVICES=3 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_2_refineCat_1" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 5 --actionness_loss_coef 3 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --enable_refine --refine_drop_saResidual --refine_cat_type 'concat1'
## baseline + refine + refine_cat_type 'concat2' :: e8 mAP: 18.322, AR@10: 10.843
CUDA_VISIBLE_DEVICES=4 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_2_refineCat_2" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 5 --actionness_loss_coef 3 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --enable_refine --refine_drop_saResidual --refine_cat_type 'concat2'




# baseline + refine + salient_loss: 
## baseline + refine + salient_loss: --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_coef 0.1 :: e44 mAP: 28.877, AR@10: 14.746
CUDA_VISIBLE_DEVICES=5 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_4_verbs_1" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 5 --actionness_loss_coef 3 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --enable_refine --refine_drop_saResidual --salient_loss --salient_loss_coef 3 --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_coef 0.1

## baseline + refine + salient_loss: --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum" --adapterCLS_conv_add_verbs_coef 0.1
CUDA_VISIBLE_DEVICES=5 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_4_verbs_3" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 5 --actionness_loss_coef 3 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --enable_refine --refine_drop_saResidual --salient_loss --salient_loss_coef 3 --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum" --adapterCLS_conv_add_verbs_coef 0.1

## baseline + refine + salient_loss: --refine_cat_type 'concat1' :: e44 mAP: 31.208, AR@10: 14.197
CUDA_VISIBLE_DEVICES=0 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_v8_4_refineCat" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 5 --actionness_loss_coef 3 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --enable_refine --refine_drop_saResidual --salient_loss --salient_loss_coef 3 --refine_cat_type 'concat1'


# DETR加一个类别无关的定位head :: e39 mAP: 15.913, AR@10: 14.279
CUDA_VISIBLE_DEVICES=4 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_actionness" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --exp_logit_scale --actionness_loss
# DETR加一个类别无关的定位head + refine :: e44 mAP: 18.699, AR@10: 14.298
CUDA_VISIBLE_DEVICES=2 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_actionness_1" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --exp_logit_scale --actionness_loss --enable_refine --refine_drop_saResidual
# DETR加一个类别无关的定位head + distillation :: e45 mAP: 29.604, AR@10: 13.426
CUDA_VISIBLE_DEVICES=2 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_actionness_distillation" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --exp_logit_scale --actionness_loss --distillation_loss --distillation_loss_coef 0.1
# DETR加一个类别无关的定位head + refine + distillation :: e46 mAP: 29.446, AR@10: 13.577
CUDA_VISIBLE_DEVICES=4 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_actionness_distillation_1" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --exp_logit_scale --actionness_loss --enable_refine --refine_drop_saResidual --distillation_loss --distillation_loss_coef 0.1
# DETR加一个类别无关的定位head + distillation + 不要ce loss --cls_loss_coef 0 :: :: e74 mAP: 28.612, AR@10: 13.916
CUDA_VISIBLE_DEVICES=5 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_actionness_distillation_2" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --exp_logit_scale --actionness_loss --distillation_loss --distillation_loss_coef 0.1 --cls_loss_coef 0



# NOTE: 手动改代码，对于actionness的情况，也是直接用roi_align的特征进行分类(除了上面两个，接下来的实验都这样设置)
## --actionness_loss :: e54 mAP: 30.432, AR@10: 13.133
CUDA_VISIBLE_DEVICES=2 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_actionness_handcraft" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --exp_logit_scale --actionness_loss
## --actionness_loss --enable_refine --refine_drop_saResidual :: e42 mAP: 30.184, AR@10: 14.068
CUDA_VISIBLE_DEVICES=5 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_actionness_handcraft_1" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --exp_logit_scale --actionness_loss --enable_refine --refine_drop_saResidual
## --actionness_loss --enable_refine --refine_drop_saResidual --cls_loss_coef 0 :: e45 mAP: 28.686, AR@10: 15.354
CUDA_VISIBLE_DEVICES=3 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_actionness_handcraft_2" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --exp_logit_scale --actionness_loss --enable_refine --refine_drop_saResidual --cls_loss_coef 0
## --actionness_loss --enable_refine --refine_drop_saResidual --dynamic_element_catch --dynamic_coef 0.1 :: e42 mAP: 28.466, AR@10: 12.713
CUDA_VISIBLE_DEVICES=7 python main.py --model_name "Thumos14_CLIP_prompt_zs_8frame_v9_actionness_handcraft_3" --cfg_path "./config/Thumos14_CLIP_zs_75_8frame.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --postprocess_type "class_agnostic" --postprocess_topk 100 --num_queries 40 --enc_layers 2 --dec_layers 4 --norm_embed --exp_logit_scale --actionness_loss --enable_refine --refine_drop_saResidual --dynamic_element_catch --dynamic_coef 0.1



# ActivityNet1.3
# 跑一下baseline :: e62 mAP: 30.832, AR@10: 45.603
CUDA_VISIBLE_DEVICES=4 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v9_1" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic


## baseline: --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 :: e78 mAP: 25.435, AR@10: 43.947
CUDA_VISIBLE_DEVICES=1 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v9_1_verbs" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1
## baseline: --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_coef 0.1 :: e41 mAP: 28.054, AR@10: 43.359
CUDA_VISIBLE_DEVICES=2 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v9_1_verbs_1" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_coef 0.1
## baseline: --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum" :: e40 mAP: 25.802, AR@10: 44.972
CUDA_VISIBLE_DEVICES=3 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v9_1_verbs_2" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum"
## baseline: --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum" --adapterCLS_conv_add_verbs_coef 0.1 :: e3 mAP: 26.533, AR@10: 39.757
CUDA_VISIBLE_DEVICES=4 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v9_1_verbs_3" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum" --adapterCLS_conv_add_verbs_coef 0.1
## baseline: --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum1" --adapterCLS_conv_add_verbs_coef 0.1 
CUDA_VISIBLE_DEVICES=2 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v9_1_verbs_4" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum1" --adapterCLS_conv_add_verbs_coef 0.1




# baseline + refine
## baseline + refine: --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 :: :: e4 mAP: 16.33, AR@10: 32.759
CUDA_VISIBLE_DEVICES=3 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v9_2_verbs" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --enable_refine --refine_drop_saResidual --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1
## baseline + refine: --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_coef 0.1 :: e3 mAP: 24.7217, AR@10: 9.381
CUDA_VISIBLE_DEVICES=4 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v9_2_verbs_1" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --enable_refine --refine_drop_saResidual --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_coef 0.1
## baseline + refine: --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum" :: e6 mAP: 24.388, AR@10: 37.677
CUDA_VISIBLE_DEVICES=5 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v9_2_verbs_2" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --enable_refine --refine_drop_saResidual --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum"
## baseline + refine: --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum" --adapterCLS_conv_add_verbs_coef 0.1 :: e5 mAP: 14.376, AR@10: 35.797
CUDA_VISIBLE_DEVICES=6 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v9_2_verbs_3" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --enable_refine --refine_drop_saResidual --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum" --adapterCLS_conv_add_verbs_coef 0.1
## baseline + refine: --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum1" --adapterCLS_conv_add_verbs_coef 0.1  :: e3 mAP: 27.168, AR@10: 39.005
CUDA_VISIBLE_DEVICES=7 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v9_2_verbs_4" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --enable_refine --refine_drop_saResidual --adapterCLS_loss --adapterCLS_type "conv_add_verbs" --adapterCLS_loss_coef 0.1 --adapterCLS_conv_add_verbs_type "sum1" --adapterCLS_conv_add_verbs_coef 0.1

# baseline + refine + concat: --enable_refine --refine_drop_saResidual --refine_cat_type 'concat1' :: e39 mAP: 29.254, AR@10: 43.123
CUDA_VISIBLE_DEVICES=5 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v6_v8_61_refine_cat_1" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 5e-5 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --actionness_loss_coef 1 --giou_loss_coef 1 --enable_refine --refine_drop_saResidual --refine_cat_type 'concat1'
# baseline + refine + concat: --enable_refine --refine_drop_saResidual --refine_cat_type 'concat2' :: e5 mAP: 29.075, AR@10: 39.169
CUDA_VISIBLE_DEVICES=1 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v6_v8_61_refine_cat_2" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 5e-5 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --actionness_loss_coef 1 --giou_loss_coef 1 --enable_refine --refine_drop_saResidual --refine_cat_type 'concat2'


## baseline + refine : --refine_cat_type 'concat1' :: e13 mAP: 28.513, AR@10: 40.939
CUDA_VISIBLE_DEVICES=1 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v9_v8_2_refine_cat_1" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --enable_refine --refine_drop_saResidual --refine_cat_type 'concat1'

## baseline + refine: --refine_cat_type 'concat1' :: e26 mAP: 30.284, AR@10: 49.520
CUDA_VISIBLE_DEVICES=7 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v9_v8_44_refine_cat_1" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 5e-5 --epochs 100 --num_queries 30 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --actionness_loss_coef 3 --enable_refine --refine_drop_saResidual --refine_cat_type 'concat1'


# baseline + refine + salience:  --refine_cat_type 'concat1' :: e24 mAP: 30.908, AR@10: 49.611
CUDA_VISIBLE_DEVICES=3 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v9_v8_38_refine_cat_1" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 5e-5 --epochs 100 --num_queries 30 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --enable_classAgnostic --actionness_loss_coef 3 --enable_refine --refine_drop_saResidual --refine_cat_type 'concat1' --salient_loss 



# actionness
## --actionness :: e9 mAP: 20.501, AR@10: 41.467
CUDA_VISIBLE_DEVICES=0 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v9_actionness" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --actionness_loss
## --actionness + refine :: e32 mAP: 21.689, AR@10: 41.328
CUDA_VISIBLE_DEVICES=2 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v9_actionness_1" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --actionness_loss --enable_refine --refine_drop_saResidual
## --actionness + distillation :: e30 mAP: 25.973, AR@10: 38.077
CUDA_VISIBLE_DEVICES=4 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v9_actionness_distillation" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --actionness_loss --distillation_loss --distillation_loss_coef 0.1
## --actionness + refine + distillation :: e38 mAP: 24.647, AR@10: 39.047
CUDA_VISIBLE_DEVICES=5 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v9_actionness_distillation_1" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --actionness_loss --enable_refine --refine_drop_saResidual --distillation_loss --distillation_loss_coef 0.1
## --actionness + distillation + 不要cls的ce loss --cls_loss_coef 0 :: e30 mAP: 25.567, AR@10: 39.49
CUDA_VISIBLE_DEVICES=5 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v9_actionness_distillation_2" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --actionness_loss --distillation_loss --distillation_loss_coef 0.1 --cls_loss_coef 0

# 下面的实验是直接crop CLIP 特征进行分类
## --actionness :: e9 mAP: 29.558, AR@10: 41.801
CUDA_VISIBLE_DEVICES=2 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v9_actionness_handcraft" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --actionness_loss
## --actionness_loss --enable_refine --refine_drop_saResidual --dynamic_element_catch --dynamic_coef 0.1 :: e7 mAP: 22.721, AR@10: 38.659
CUDA_VISIBLE_DEVICES=3 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v9_actionness_handcraft_3" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --save_result --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --norm_embed --exp_logit_scale --proposals_weight_type "after_softmax" --actionness_loss --enable_refine --refine_drop_saResidual --dynamic_element_catch --dynamic_coef 0.1