echo "12个实验后台执行开始, Compute Node: 209 ....."
# 【base-v2-7】 --instance_loss --semantic_vhead_type "Conv" --semantic_thead_type "MHA" --augment_prompt_type "attention" --subaction_version "v3" --lr_semantic_head 1e-7 :: 
CUDA_VISIBLE_DEVICES=4 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v4_6" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --use_mlflow --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --exp_logit_scale --instance_loss --semantic_vhead_type "Conv" --semantic_thead_type "MHA" --augment_prompt_type "attention" --subaction_version "v3" --lr_semantic_head 1e-7 &
sleep 3
# 【base-v2-7】 --instance_loss --semantic_vhead_type "Enc" --semantic_thead_type "MHA" --augment_prompt_type "attention" --subaction_version "v3" --lr_semantic_head 1e-7 :: 
CUDA_VISIBLE_DEVICES=4 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v4_7" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --use_mlflow --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --exp_logit_scale --instance_loss --semantic_vhead_type "Enc" --semantic_thead_type "MHA" --augment_prompt_type "attention" --subaction_version "v3" --lr_semantic_head 1e-7 &
sleep 3
# 【base-v2-7】 --instance_loss --semantic_vhead_type "None" --semantic_thead_type "MHA" --augment_prompt_type "attention" --subaction_version "v3" --lr_semantic_head 1e-7 :: 
CUDA_VISIBLE_DEVICES=4 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v4_8" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --use_mlflow --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --exp_logit_scale --instance_loss --semantic_vhead_type "None" --semantic_thead_type "MHA" --augment_prompt_type "attention" --subaction_version "v3" --lr_semantic_head 1e-7 &
sleep 3
# 【base-v2-7】 --instance_loss --semantic_vhead_type "Conv" --semantic_thead_type "MHA" --augment_prompt_type "attention" --subaction_version "v3" --lr_semantic_head 1e-6 :: 
CUDA_VISIBLE_DEVICES=5 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v4_9" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --use_mlflow --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --exp_logit_scale --instance_loss --semantic_vhead_type "Conv" --semantic_thead_type "MHA" --augment_prompt_type "attention" --subaction_version "v3" --lr_semantic_head 1e-6 &
sleep 3
# 【base-v2-7】 --instance_loss --semantic_vhead_type "Enc" --semantic_thead_type "MHA" --augment_prompt_type "attention" --subaction_version "v3" --lr_semantic_head 1e-6 :: 
CUDA_VISIBLE_DEVICES=5 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v4_10" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --use_mlflow --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --exp_logit_scale --instance_loss --semantic_vhead_type "Enc" --semantic_thead_type "MHA" --augment_prompt_type "attention" --subaction_version "v3" --lr_semantic_head 1e-6 &
sleep 3
# 【base-v2-7】 --instance_loss --semantic_vhead_type "None" --semantic_thead_type "MHA" --augment_prompt_type "attention" --subaction_version "v3" --lr_semantic_head 1e-6 :: 
CUDA_VISIBLE_DEVICES=5 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v4_11" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --use_mlflow --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --exp_logit_scale --instance_loss --semantic_vhead_type "None" --semantic_thead_type "MHA" --augment_prompt_type "attention" --subaction_version "v3" --lr_semantic_head 1e-6 &
sleep 3
# 【base-v2-7】 --instance_loss --semantic_vhead_type "Conv" --augment_prompt_type "single" --lr_semantic_head 1e-7 :: 
CUDA_VISIBLE_DEVICES=6 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v4_12" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --use_mlflow --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --exp_logit_scale --instance_loss --semantic_vhead_type "Conv" --augment_prompt_type "single" --lr_semantic_head 1e-7 &
sleep 3
# 【base-v2-7】 --instance_loss --semantic_vhead_type "Enc" --augment_prompt_type "single" --lr_semantic_head 1e-7 :: 
CUDA_VISIBLE_DEVICES=6 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v4_13" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --use_mlflow --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --exp_logit_scale --instance_loss --semantic_vhead_type "Enc" --augment_prompt_type "single" --lr_semantic_head 1e-7 &
sleep 3
# 【base-v2-7】 --instance_loss --semantic_vhead_type "Conv" --augment_prompt_type "single" --lr_semantic_head 1e-6 :: 
CUDA_VISIBLE_DEVICES=6 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v4_14" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --use_mlflow --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --exp_logit_scale --instance_loss --semantic_vhead_type "Conv" --augment_prompt_type "single" --lr_semantic_head 1e-6 &
sleep 3
# 【base-v2-7】 --instance_loss --semantic_vhead_type "Enc" --augment_prompt_type "single" --lr_semantic_head 1e-6 :: 
CUDA_VISIBLE_DEVICES=7 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v4_15" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --use_mlflow --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --exp_logit_scale --instance_loss --semantic_vhead_type "Enc" --augment_prompt_type "single" --lr_semantic_head 1e-6 &
sleep 3
# 【base-v2-7】 --instance_loss --semantic_vhead_type "Conv" --augment_prompt_type "single" --lr_semantic_head 1e-5 :: 
CUDA_VISIBLE_DEVICES=7 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v4_16" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --use_mlflow --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --exp_logit_scale --instance_loss --semantic_vhead_type "Conv" --augment_prompt_type "single" --lr_semantic_head 1e-5 &
sleep 3
# 【base-v2-7】 --instance_loss --semantic_vhead_type "Enc" --augment_prompt_type "single" --lr_semantic_head 1e-5 :: 
CUDA_VISIBLE_DEVICES=7 python main.py --model_name "ActivityNet13_CLIP_prompt_zs_v4_17" --cfg_path "./config/ActivityNet13_CLIP_zs_75.yaml" --use_mlflow --batch_size 16 --target_type "prompt" --lr 1e-4 --epochs 100 --num_queries 5 --postprocess_type "class_agnostic" --postprocess_topk 100 --rescale_length 300 --enc_layers 2 --dec_layers 2 --enable_backbone --lr_backbone 1e-2 --exp_logit_scale --instance_loss --semantic_vhead_type "Enc" --augment_prompt_type "single" --lr_semantic_head 1e-5 &
wait
echo "12个实验后台执行结束, Compute Node: 209 ....."