# basic
task: "close_set"

# dataset
dataset_name: Thumos14
anno_file_path: "./data/Thumos14/Thumos14_annotations.json"
feature_info_path: "./data/Thumos14/CLIP/Thumos14_info.json"
description_file_path: "./data/Thumos14/Thumos14_description_v4.json"
feature_path: "/mnt/Datasets/Thumos14/CLIP_feature"
feature_stride: 16
feature_type: "CLIP"
num_classes: 20

